name: Java CI/CD Pipeline with Gradle

# Khi nào pipeline chạy: mỗi khi có push hoặc pull request vào nhánh main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23' # Thay đổi nếu bạn dùng version khác
          distribution: 'temurin'

      # Bước 3: Cấp quyền thực thi cho Gradle wrapper (nếu có)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Bước 4: Build ứng dụng với Gradle
      - name: Build with Gradle
        run: ./gradlew build -x test # Build mà không chạy test

      # Bước 5: Chạy test
      - name: Run tests
        run: ./gradlew test

      # Bước 6: Lưu trữ artifact (file .jar hoặc .war đã build)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: build/libs/*.jar # Đường dẫn mặc định của Gradle cho file JAR
